// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3CEl_VDAhefXBVMwh8HQby26mR5cSCMk',
    appId: '1:1063535954462:web:b62409b777670953343c0f',
    messagingSenderId: '1063535954462',
    projectId: 'lucid-mobile-shop',
    authDomain: 'lucid-mobile-shop.firebaseapp.com',
    storageBucket: 'lucid-mobile-shop.appspot.com',
    measurementId: 'G-BR59LGC0CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiShqKE8qwY9VKAfUWaIo7HYmpSukV4OY',
    appId: '1:1063535954462:android:6da19e2647b0406c343c0f',
    messagingSenderId: '1063535954462',
    projectId: 'lucid-mobile-shop',
    storageBucket: 'lucid-mobile-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4OyF1OZVmKRo3BhyvHX0Aw3B_wvK6h0',
    appId: '1:1063535954462:ios:ed85d4a70f8ade15343c0f',
    messagingSenderId: '1063535954462',
    projectId: 'lucid-mobile-shop',
    storageBucket: 'lucid-mobile-shop.appspot.com',
    iosClientId: '1063535954462-ps92gur5n3ipmnqqf137sc7hbtalt41j.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileShop',
  );
}
